In [1]:
import numpy as np
from pandas  import DataFrame, Series
import matplotlib.pyplot as plt

import re
from datetime import timedelta, datetime

In [2]:
import pandas as pd 
pd.options.display.max_columns = 50

In [3]:
root = "/Users/Lam/PycharmProjects/untitled/aws/"
# root = "/Users/Lam/Downloads/"
file_name = root + "temp.log"
# print(file_name)
# lines = [line.rstrip('\n') for line in open(file_name)]

In [4]:
f = open(file_name, 'r')
regex = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(.*) (\/(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)'
result = re.findall(regex, f.read())

In [5]:
df = pd.DataFrame(result)
df = df.drop([1] , axis=1)
display(df.tail(20))

                          0                                                  2
893009  2019-07-23T23:59:54  /api/touroku/raininfopro.html?os=Android&devic...
893010  2019-07-23T23:59:55  /api/touroku/raininfopro.html?os=Android&devic...
893011  2019-07-23T23:59:55  /api/touroku/raininfopro.html?os=Android&devic...
893012  2019-07-23T23:59:55  /api/touroku/raininfopro.html?os=Android&devic...
893013  2019-07-23T23:59:56  /api/touroku/raininfopro.html?os=Android&devic...
893014  2019-07-23T23:59:56  /api/touroku/raininfopro.html?os=Android&devic...
893015  2019-07-23T23:59:56  /api/touroku/raininfopro.html?os=Android&devic...
893016  2019-07-23T23:59:57  /api/touroku/raininfopro.html?os=Android&devic...
893017  2019-07-23T23:59:57  /api/touroku/raininfopro.html?os=Android&devic...
893018  2019-07-23T23:59:57  /api/touroku/raininfopro.html?os=Android&devic...
893019  2019-07-23T23:59:57  /api/touroku/raininfopro.html?os=Android&devic...
893020  2019-07-23T23:59:57  /api/touroku/raininfopro.html?os=Android&devic...
893021  2019-07-23T23:59:58  /api/touroku/raininfopro.html?os=Android&devic...
893022  2019-07-23T23:59:58  /api/touroku/raininfopro.html?os=Android&devic...
893023  2019-07-23T23:59:58  /api/touroku/raininfopro.html?os=Android&devic...
893024  2019-07-23T23:59:59  /api/touroku/raininfopro.html?os=Android&devic...
893025  2019-07-23T23:59:59  /api/touroku/raininfopro.html?os=Android&devic...
893026  2019-07-23T23:59:59  /api/touroku/raininfopro.html?os=Android&devic...
893027  2019-07-23T23:59:59  /api/touroku/raininfopro.html?os=Android&devic...
893028  2019-07-23T23:59:59  /api/touroku/raininfopro.html?os=Android&devic...

In [6]:
df.columns = ['Request_Time', 'Url']
df['Request_Time'] = pd.to_datetime(df['Request_Time'], format='%Y-%m-%dT%H:%M:%S')
df['device_uuid'] = np.nan
df['device_os'] = np.nan
df['device_name']  = np.nan
df['app_version'] = np.nan

display(df.tail(20))

,Request_Time,Url,device_uuid,device_os,device_name,app_version
893009,2019-07-23 23:59:54,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893010,2019-07-23 23:59:55,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893011,2019-07-23 23:59:55,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893012,2019-07-23 23:59:55,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893013,2019-07-23 23:59:56,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893014,2019-07-23 23:59:56,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893015,2019-07-23 23:59:56,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893016,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893017,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893018,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893019,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893020,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893021,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893022,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893023,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893024,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893025,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893026,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893027,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN
893028,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,NaN,NaN,NaN,NaN

In [18]:

# df['Counts'] = 1
import urllib.parse as urlparse
title = ['device_uuid','device_os','device_name','app_version']
def update_url(url, name):
    parsed = urlparse.urlparse(url)
    try: 
        return ''.join(urlparse.parse_qs(parsed.query)[name])
    except KeyError: 
        return np.nan


df['device_uuid'] = df['Url'].apply(update_url, name=title[0])
df['device_os'] =  df['Url'].apply(update_url,name=title[1])
df['device_name'] =  df['Url'].apply(update_url,name=title[2])
df['app_version'] =  df['Url'].apply(update_url,name=title[3])

display(df.tail(10))

,Request_Time,Url,device_uuid,device_os,device_name,app_version
893019,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,353021081703604,8.0.0,KDDI_SHV40,5.2
893020,2019-07-23 23:59:57,/api/touroku/raininfopro.html?os=Android&devic...,QV706DAU1H,9,KDDI_SOV37,5.2
893021,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,CB512G05HE,9,KDDI_SOV38,5.2
893022,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,759208318605,8.1.0,KYOCERA_KYV41,5.2
893023,2019-07-23 23:59:58,/api/touroku/raininfopro.html?os=Android&devic...,QV713RP21L,9,KDDI_SOV39,5.2
893024,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,QV701W6Y1H,9,KDDI_SOV37,5.2
893025,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,BH9009X299,8.0.0,KDDI_SOV36,5.2
893026,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,CB512FYG2N,9,KDDI_SOV38,5.2
893027,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,258da28814057ece,8.0.0,KDDI_SCV38,5.2
893028,2019-07-23 23:59:59,/api/touroku/raininfopro.html?os=Android&devic...,QV70B93W11,9,KDDI_SOV36,5.2

In [19]:
result = df.groupby(['device_uuid']).count().sort_values(['app_version'],ascending=False)
display(result.head(30))

                    Request_Time   Url  device_os  device_name  app_version
device_uuid
259708173140                1509  1509       1509         1509         1509
259708102571                 724   724        724          724          724
5a62577c                     485   485        485          485          485
356113072677439              367   367        367          367          367
356124070402050              281   281        281          281          281
356106071154525              228   228        228          228          228
259708168978                 224   224        224          224          224
259708120191                 194   194        194          194          194
259708102717                 184   184        184          184          184
259708538041                 179   179        179          179          179
259708343301                 170   170        170          170          170
259708175917                 169   169        169          169          169
356105071005018              163   163        163          163          163
259708125219                 152   152        152          152          152
259708130455                 150   150        150          150          150
356113070331187              143   143        143          143          143
3JQ7N18B06001777             133   133        133          133          133
228ac56631017ece             129   129        129          129          129
759208508863                 123   123        123          123          123
4c9e841f                     121   121        121          121          121
356124070589260              120   120        120          120          120
353006080838121              119   119        119          119          119
790908517741                 119   119        119          119          119
QV70C1P011                   116   116        116          116          116
259708156903                 116   116        116          116          116
98899b444f4c593256           115   115        115          115          115
BH904X5499                   115   115        115          115          115
353492090257504              115   115        115          115          115
356113073063449              114   114        114          114          114
QV707AHE1H                   113   113        113          113          113

In [20]:
result = df.rename(columns={'device_name':'count'})[['device_uuid','Request_Time',"app_version",'device_os','count']].groupby(['device_uuid',pd.Grouper(key='Request_Time', freq='1H'),"app_version",'device_os']).count().sort_values(['count'],ascending=False)
display(result.head(30))

                                                           count
device_uuid     Request_Time        app_version device_os
259708173140    2019-07-23 00:00:00 5.1         6.0.1        421
                2019-07-23 01:00:00 5.1         6.0.1        294
259708102571    2019-07-23 09:00:00 5.2         6.0.1        173
259708173140    2019-07-23 23:00:00 5.1         6.0.1        152
259708102571    2019-07-23 01:00:00 5.2         6.0.1        136
                2019-07-23 00:00:00 5.2         6.0.1        114
259708173140    2019-07-23 22:00:00 5.1         6.0.1        109
259708102571    2019-07-23 11:00:00 5.2         6.0.1        100
259708173140    2019-07-23 21:00:00 5.1         6.0.1         89
259708102571    2019-07-23 02:00:00 5.2         6.0.1         87
                2019-07-23 10:00:00 5.2         6.0.1         84
259708173140    2019-07-23 13:00:00 5.1         6.0.1         83
5a62577c        2019-07-23 22:00:00 5.2         6.0.1         78
                2019-07-23 23:00:00 5.2         6.0.1         69
356113072677439 2019-07-23 15:00:00 5.1         6.0.1         62
259708173140    2019-07-23 12:00:00 5.1         6.0.1         61
5a62577c        2019-07-23 21:00:00 5.2         6.0.1         59
259708168978    2019-07-23 17:00:00 5.2         6.0.1         56
356113072677439 2019-07-23 16:00:00 5.1         6.0.1         56
                2019-07-23 14:00:00 5.1         6.0.1         54
259708173140    2019-07-23 20:00:00 5.1         6.0.1         53
                2019-07-23 11:00:00 5.1         6.0.1         45
5a62577c        2019-07-23 17:00:00 5.2         6.0.1         44
259708168702    2019-07-23 14:00:00 5.2         6.0.1         42
259708168978    2019-07-23 16:00:00 5.2         6.0.1         41
5a62577c        2019-07-23 19:00:00 5.2         6.0.1         41
                2019-07-23 18:00:00 5.2         6.0.1         40
                2019-07-23 20:00:00 5.2         6.0.1         37
356113072677439 2019-07-23 07:00:00 5.1         6.0.1         37
5a62577c        2019-07-23 16:00:00 5.2         6.0.1         36

In [ ]:
result = df.rename(columns={'device_name':'count'})[['device_uuid','Request_Time',"app_version",'device_os','count']].groupby(['device_uuid',pd.Grouper(key='Request_Time', freq='1D'),"app_version",'device_os']).count().sort_values(['count'],ascending=False)
display(result.head(30))